manifest: add patch version to the manifest
Starting from 2021.6 it's required to to also have the patch number
included in in the version in the manifest.

This fixes the error below when trying to reload the server:
Error: Platform error light.plejd - Integration 'plejd' not found.

Signed-off-by: Joakim Bech <joakim.bech@gmail.com>